### ISSUE TITLE
Tiler catches Range check error at the end of GlobalTiling

### ISSUE THREAD

**Issue by hitomi2500** [gligli/tiler#3]
Tiler keeps crashing at the end of GlobalTiling if i process a big (>50) number of frames. For small numbers, tiler behaves flawlessly. Sometimes it crashes in a different place. Tested with a different files, different computers. Backtracked to the older version of tiler (december 2021) stepping 10-15 commits at a time into the past. Crash persist.

![изображение](https://user-images.githubusercontent.com/11516784/181224551-24d29b67-7772-493a-9e3b-e756f7905957.png)

**Comment by gligli** [comment]
Hello, could you make your video file (.mp4) available?

**Comment by gligli** [comment]
Actually, I think commit 43953adb4261801341d8ff670f83e69b807118c8 should fix it!

**Comment by hitomi2500** [comment]
Thank you very much! The encoding is not finished yet, but it passed through global tiling without any issues. I'm attaching the video file just in case.
https://user-images.githubusercontent.com/11516784/181684721-43e01e23-2eec-46e8-802e-319dd361c0a6.mp4

I will do more testing and close the issue if everything's fine.

**Comment by hitomi2500** [comment]
Works like a charm, thank you again, closing the issue.
